### ISSUE TITLE
Set up build/lint infrastructure

### ISSUE THREAD

**Issue by sgomes** [google/material-design-lite#4464]
- [x] Keep current lint file, modify to work in new directory structure
- [x] Implement JS linting
- [x] Implement CSS linting
- [x] Add npm script to run js + css linting
- [x] Fix any invalid files
- [x] Remove gulpfile and related packages
- [x] Set up webpack config
- [x] Set up Greenkeeper
- [x] Set up validate-commit-msg
- [x] Ensure all contributing docs are up to date.
- [x] Modify CI config

**Comment by Garbee** [comment]
We may want to add this on our CI end. https://dependencyci.com/ Just as an extra layer to handle any updates/community additions going forward.

**Comment by traviskaufman** [comment]
It looks like [Greenkeeper](https://greenkeeper.io) seems to be the most powerful and recommended dep mgmt tool for JS projects, so I think I'm going to investigate using it.

Furthermore, we should probably decide on commit message guidelines as well. Angular has [widely adopted commit message guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines) which I think would be a good choice for us. We can use [validate-commit-msg](https://github.com/kentcdodds/validate-commit-msg) to enforce it, and recommend tools like [commitizen](https://www.npmjs.com/package/commitizen) to make it super easy for contributors. This will help us with things like [changelogs](https://github.com/conventional-changelog/conventional-changelog), for example.

Furthermore if we want to integrate tools like semantic-release (see #4565) in the future, having these conventions in place makes it really easy.

**Comment by sgomes** [comment]
+1 to Greenkeeper. David-dm is useful, but having PRs opened automatically sounds useful, and the fact that it's the recommended tool gives us a bit more confidence.

+1 to commit messages, particularly if we can have a good error message to teach folks committing for the first time.

semantic-release bears some investigation, but I'm concerned how much work it would take on for us. In a project with our current size, we probably want to keep a fair amount of control over release notes, versioning, release pushing, etc. Packaging and generating changelogs (which we'd then copy into the release notes) sounds like something we could definitely add some automation to, though.

**Comment by traviskaufman** [comment]
Greenkeeper ticket: #4572
