### ISSUE TITLE
Broadcast info on v2 plans to devs

### ISSUE THREAD

**Issue by sgomes** [google/material-design-lite#4466]
- [x] Mock up README changes
- [ ] Mock up post
- [ ] Figure out communication channel

**Comment by rfru** [comment]
Post and other comms will be for alpha or later stage.

**Comment by Garbee** [comment]
Marked to Alpha since that would be a good starting point. Whether we do it right away or after 2/3 releases in isn't a big deal.

**Comment by sgomes** [comment]
Closed with the announcement of MDC-Web.
