### ISSUE TITLE
Implement Toolbar v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4480]
- [ ] No-Seam / Static
- [ ] Seam Always / Fixed

---
- [ ] No-Seam -> Seam + Fixed / Waterfall
- [ ] Flexible Header

Spec reference: https://www.google.com/design/spec/components/toolbars.html

**Comment by Garbee** [comment]
One thing we need to consider with v2 is the active state of buttons on toolbars. There are two good choices to go with.

The first is using the [accent color for the border](http://codepen.io/Garbee/pen/BjLvPw). This is a direct overlay on top of the platforms native active state of having a light-blue outline. However, it looks out of place with the rest of the active states we currently have.

The second method is applying the [same shade](http://codepen.io/Garbee/pen/mEqJOB) we do to buttons/fabs. This is 12% of black.  This keeps consistency and still provides a good state indicator.

**Comment by Garbee** [comment]
Dumping my assignment on this due to a new project getting my attention fully.

Basic idea I came up with that should work though is, `position:sticky` by default for the static navbar with JS-enhanced for non-supporting browsers. Developers can then include a polyfill for sticky if they wish as well to avoid our fallback from running.

`garbee/feature/toolbar` has some initial working sample code towards this method. Unsure about Webkit support however.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/38
