### ISSUE TITLE
Implement "FAB-toolbar" v2 component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4482]
- Spec reference: https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions
- Motion video mock: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B8v7jImPsDi-NXNEaXZ0Um1yc0k/components-buttons-fab-transition_toolbar_01.webm
- [ ] X & Y positions that FAB moves to needs clarification
- [ ] Implement Bottom FAB menu component
- [ ] Implement Proper transitions between FAB and Toolbar

There are internal motion mocks for these transitions that I can get when it comes time to implement.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/36
