### ISSUE TITLE
Migrate to object composition pattern from mixin pattern

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4569]
Follow-up of #4568 

- [x] Migrate existing components
- [x] Migrate existing examples
- [x] Update docs/DEVELOPER.md with this info.
