### ISSUE TITLE
Create "reset" / "defaults" styles lib

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4652]
``` html
<html class="mdl-reset">
  <!-- .... -->
</html>
```

``` scss
.mdl-reset {
  @include mdl-typography;

  h1 {
    @include mdl-typography-...
  }

  h2 {
    // ...
  }
}
```

**Comment by traviskaufman** [comment]
link styling needs design guidance

**Comment by traviskaufman** [comment]
- [ ] Link styles
- [ ] Typography
- [ ] Set Roboto Font
- [ ] 4px grid alignment - Normalize margins/padding on `document.body`, block-level elements
- [ ] List styling
- [ ] Tables (make sure they look clean, e.g. `border-collapse`)

**Comment by Garbee** [comment]
If we have `mdl-typography` why do we need a reset class?

I feel like everything mentioned here would easily fall under one global helper class.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/42
