### ISSUE TITLE
Properly namespace all components

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4837]
Currently, our system is as such:

``` js
// mdl-component/index.js
import {ComponentFoundation} from './foundation';

export {ComponentFoundation};

export default class Component ...
```

``` js
// material-design-lite/index.js
import Component from 'mdl-component';

autoInit.register('MDLComponent', Component);

export {
  // ...
  Component
};
```

This presents some issues due to the way we're exporting the components.

Using a ES2015 + babel environment:

``` js
import Component from 'mdl-component';
```

Using any other environment:

``` js
const Component = require('mdl-component').default;
```

This ambiguity between which one to use is sub-optimal. Furthermore, it's strange to have the Foundation class attached as an export to the component class.

Let's switch to namespaces instead:

``` js
// mdl-component/index.js
import {ComponentFoundation} from './foundation';

export {ComponentFoundation};

export class Component ...
```

``` js
// material-design-lite/index.js
import * as component from 'mdl-component';

autoInit.register('MDLComponent', component.Component);

export {
  // ...
  component
};
```

This creates a homogeneous interface whether or not you're using the built library, ES2015 + babel, or no babel and a different module system.

``` js
// ES2015 (Babel or non-babel)
import {Component, ComponentFoundation} from 'mdl-component';

// CommonJS
const {Component, ComponentFoundation} = require('mdl-component');

// AMD
require('/path/to/mdl-component', ({Component, ComponentFoundation}) => { /* ... */ });

// Global (Either using full mdl built or individual per-component)
const {Component, ComponentFoundation} = mdl.component;
```
## Changes
- [x] Modify webpack config to export lowercase symbols for component
- [x] Modify all source code and tests
- [x] Update examples
- [x] Update demos
- [x] Update any documentation which talks about how we export components
