### ISSUE TITLE
1.0.0 Release checklist

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#690]
- [x] Check license file headers are present on all files (per OSS review) [addy]
- [x] Bump bower.json and package.json [addy]
- [x] Tag release (depends on items 1 and 2) [addy]
- [x] Publish release assets to CDN [marc] (done circa Sun, will refresh on Mon)
- [x] Publish site to final destination [marc] checking the previous item picked this up
- [x] Check we've correctly output all the theme generated files [surma]
- [x] Run https://www.npmjs.com/package/broken-link-checker or similar against the site. Check for broken links [surma]
- [x] Publish to npm & check release can be `bower` or `npm install`'d (this may have to wait for Monday morning so we don't prematurely get it out there) [addy]
- [x] Author release blog post [addy]
- [x] Publish blog post [addy]
- [x] Test _all_ templates in _all_ browsers (Looking at you, lynx)
- [x] Test prod publication flow by promoting from staging to http://mdlite.io [marc]
- [x] need a guideline for triaging bugs (issue template) [sgomes]
- [x] check analytics [Surma]
- [x] verify cloud storage access logging [Marc, Alex] (will need to use dremel)
- [x] wrap up rest of release process [Addy]
- [x] quick perf testing [sgomes]
- [x] setup 3-4 war room [Marc]
- [x] setup meeting w/ Katie [Marc]
- [x] runsequence on publish:code to make sure zip file built before push to cloud [Marc]
- [x] good to share file size somewhere on microsite [Surma]
- [x] don't include all color combo css files in mdl.zip [Marc]
- [x] verify that assets in tag are same as assets in zip file [Marc & Addy]

cc @surma @marcacohen Feel free to edit the list as needed or change names on items. Just a guess of what might work here :)

**Comment by MikeMitterer** [comment]
@addyosmani Can you please add a link to my Dart-Site: http://www.material-design-lite.pub/
Thanks + Congrats to the upcoming V1.0

**Comment by addyosmani** [comment]
Thanks! Also appreciate you keeping the port up to date. I think the best
place for the Dart port would be in the FAQ. We could include an item which
also appears in the TOC "Is there a Dart port of Material Design Lite
available?" and then include text and a link about the project there. Imo,
it's where I'd go to look for info on ports personally.

**Comment by Garbee** [comment]
Or we could have a page/section for ports of any kind. Relating to #753 we could have a place listing projects that bring MDL to other systems easier and ports to other languages. Keep all of that centralized and easy to categorize.

**Comment by marcacohen** [comment]
To minimize proliferation of pages, I would vote for starting small, with
the Dart FAQ that Addy described. As and when we get additional ports, we
can add additional bullets to a more general FAQ or add a new category of
FAQs. And when MDL is so wildly successful we outgrow the FAQ page
entirely, then we can easily migrate this content a dedicated page. But
taking it one step at a time would be my suggestion.

On Tue, Jul 7, 2015 at 12:05 AM, Jonathan Garbee <notifications@github.com>
wrote:

> Or we could have a page/section for ports of any kind. Relating to #753
> <https://github.com/google/material-design-lite/issues/753> we could have
> a place listing projects that bring MDL to other systems easier and ports
> to other languages. Keep all of that centralized and easy to categorize.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/material-design-lite/issues/690#issuecomment-119023533>
> .
>



-- 
Marc Cohen
http://about.me/marc1

**Comment by Garbee** [comment]
Closing this off since all the points are addressed.
